
  var pagePrepend = '';


$(window).scroll(function(){
    if ($(window).scrollTop() >= 0) {
       $('nav').addClass('fixed-header');
    }
    else {
       $('nav').removeClass('fixed-header');
    }
});

function alignItems() {
  figure = parseInt($('.website').css('width'), 10);
  pic = parseInt($('.design-img').css('width'), 10);
  finalWidth = String((figure - pic) / 2) + 'px';
  $('.website-title').css('margin-left', finalWidth);
  $('.website-description').css('margin-left', finalWidth);
  $('.website-description').css('margin-right', finalWidth);
}

function disableAndEnableImgs(mode) {
  if (mode == 'disable') {
    $('figcaption').removeClass('figcaption-cls')
    $('img').removeClass('img-cls')
  }
  else {
    $('figcaption').addClass('figcaption-cls')
    $('img').addClass('img-cls')
  }
}

$(document).ready(function() {
  alignItems();
});

$(window).resize(function() {
  alignItems();
});

function openNav() {
    document.getElementById("mySidenav").style.width = "100%";
    $('#open-button').css("display", 'none');
    $('#close-button').css("display", 'block');
    $('#header-description').css("display", 'none');
    disableAndEnableImgs('disable');
}

function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
    $('#open-button').css("display", 'block');
    $('#close-button').css("display", 'none');
    $('#header-description').css("display", 'block');
    disableAndEnableImgs('enable');
}


Vue.component('banner', {
  template: `<div id='index-header' class='header-strip'>
    <span id="header-info">
      
      <span id='header-description'>
        
        <a v-for="page in designPage" v-bind:href='page.url'>{{ page.label }} </a> - 
        <a v-for="page in developerPage" v-bind:href='page.url'>{{ page.label }} </a> 
      </span>
    </span>
    <i id="open-button" class="menu-icon fa fa-bars fa-2x" aria-hidden="true" onclick="openNav()"></i>
    <i id="close-button" class="menu-icon fa fa-times fa-2x" aria-hidden="true" onclick="closeNav()"></i>
  </div>
  `,
  data: function () {
    var data = {

      designPage: [
        { label: 'FutureByDesign', url: pagePrepend + 'design.html' },
      ],
      developerPage: [
        { label: 'Developer', url: pagePrepend + 'development.html' },
      ],
      indexPage: [
        { },
      ]
    };
    return data;
  },
});

new Vue({
  el: '#my-projects',
  data: {
    projects: [
        { title: 'DeepFake Detection Challenge', url: 'https://www.kaggle.com/c/deepfake-detection-challengep', description: 'Currently I participate in Kaggle’s DeepFake Detection Challenge joined by AWS, Facebook, and Microsoft. ' +
        'I’m training models and using TensorFlow to identify fake faces in videos.DeepFake uses deep learning technology like Deep Artificial Neural Networks to put someone else’s faces onto the person in the image or video. ' +
        'The resulting fake content is usually very convincing it could easily jeopardize media integrity. Therefore detecting DeepFake is essential.Previously I’ve done TensorFlow’s project of training Neural Network model in classifying shoes ' +
        'and shirts using Kaggle’s Fashion MNIST dataset; Similar techniques could be applied here and build upon. In addition, detecting fake faces in videos would be a lot more challenging; it requires capturing faces in motion, ' +
        'and training models to identify faces generated by DeepFake. Screening images as training datasets is key to building effective ML models, and I’m using the 1 million fake faces dataset posted on Kaggle for development and validation.' },

        { title: 'Medical Image Classification and AI’s Application in Healthcare', url: 'https://github.com/aq13579/count-ascii-freq', description: 'Leveraging ML models helps doctors diagnose diseases like diabetic eye disease and metastatic breast cancer. ' +
      'The research could be categorized in the following steps — Problem Selection, Data Collection, ML Development, Validation, Assessment of Impact, Deployment and Monitoring.Researchers in the paper discussed the many challenges in developing ML model out ' +
        'of screening patient images, and emphasized the importance of working closely with clinical experts. For instance, making sure reference standard is accurate, adjusting validation matrix depending on patients demographics, continuing monitoring of ' +
        'unexpected error in real use… With these taken care in mind, the paper concluded that ML application in healthcare will greatly improve diagnosis: reduction in false negatives in treatment; higher review speed, ' +
        'reduced false negatives in treatment.' },

      { title: 'Using AI to predict flight delay in airports around the world', url: 'https://github.com/aq13579/tic-tac-toe-game-app#tic-tac-toe-game-app', description: 'Javascript built tic tac toe game app'},
      { title: 'Translation between Spanish and English', url: 'https://www.tensorflow.org/tutorials/text/nmt_with_attention', description: 'Used TensorFlow and Trained sequence-to-sequence models to translate between Spanish and English'},
       ]
  }
});

new Vue({
  el: '#my-websites',
  data: {
    websites: [

      { title: 'ADI', img: 'img/designs/gimmeCookie.jpg', demo: 'https://adicu.com/',  description: 'Meet up with fellow coders to discuss projects and entreprenuer ideas, develop apps, built website from scratch for student organization and clubs on campus. And eat cookies' },
      { title: '3D Animation', img: 'img/designs/blueskystudio.png', demo: 'http://blueskystudios.com/',  description: 'Visited Blue Sky Studio to learn about 3D animation,Use Autodesk to design interior and  how they sculpture character, then use software to animate, tried out their 3D theatre on their new film "Ice Age 2"' },
      { title: 'RoboCup', img: 'img/designs/robocup.png', demo: 'https://2019.robocup.org//',  description: 'Built robots that could navigate a maze with 2 floors, competed in Rescue challenge in the Robocup Invitations' },
      { title: 'Eindhoven Panel Presentation', img: 'img/designs/eindhoven.png', demo: 'https://2019.robocup.org//', description: 'Presentation at Eindhoven University on machine learning and artificial intelligence and sensors' },
      { title: 'Food Bank for NYC', img: 'img/designs/foodbank.png', demo: 'https://volunteer.foodbanknyc.org/',  description: 'Volunteer at non-profit to provide food for kids and family in need' },
    ]
  }
});



new Vue({
  el: '#header'
});

if (!isIndex()) {
  $('#header-info').css("display", "block");
}
else {
  $('#header-info').css("display", "none");
}